// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {color} from '../models';
import {main} from '../models';

export function Apply(arg1:color.Settings):Promise<main.State>;

export function ApplyPreset(arg1:string):Promise<main.State>;

export function DeleteProfile(arg1:string):Promise<main.State>;

export function ExportConfig():Promise<main.State>;

export function GetState():Promise<main.State>;

export function ImportConfig():Promise<main.State>;

export function Reset():Promise<main.State>;

export function SaveProfile(arg1:string):Promise<main.State>;

export function SelectDisplay(arg1:string):Promise<main.State>;

export function SetAutostart(arg1:boolean):Promise<main.State>;
