// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1) {
  return window['go']['main']['App']['Apply'](arg1);
}

export function ApplyPreset(arg1) {
  return window['go']['main']['App']['ApplyPreset'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SelectDisplay(arg1) {
  return window['go']['main']['App']['SelectDisplay'](arg1);
}
