// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {color} from '../models';
import {main} from '../models';

export function Apply(arg1:color.Settings):Promise<main.State>;

export function GetState():Promise<main.State>;

export function Reset():Promise<main.State>;

export function SelectDisplay(arg1:string):Promise<main.State>;
